insert into version values (1);
create sequence hibernate_sequence start with 1 increment by 1;
create table ApplicationAccount (id bigint not null, gitHubToken varchar(255), userName varchar(255), primary key (id));
create table GitHubUser (id bigint not null, avatar_url varchar(255), events_url varchar(255), followers_url varchar(255), following_url varchar(255), gists_url varchar(255), gravatar_id varchar(255), html_url varchar(255), login varchar(255) UNIQUE, organizations_url varchar(255), received_events_url varchar(255), repos_url varchar(255), site_admin boolean not null, starred_url varchar(255), subscriptions_url varchar(255), type varchar(255), url varchar(255), primary key (id));
create table Notification (jpaId bigint not null, id bigint, last_read_at timestamp, reason varchar(255), unread boolean not null, updated_at timestamp, url varchar(255), userId varchar(255), repository_jpaId bigint, subject_jpaId bigint, primary key (jpaId));
create table NotificationMetaData (id bigint not null, eTag varchar(255), lastModified varchar(255), lastTested timestamp, rateLimit integer not null, rateLimitRemaining integer not null, rateLimitReset integer not null, applicationAccount_id bigint, primary key (id));
create table NotificationSubject (jpaId bigint not null, id bigint, latest_comment_url varchar(255), title varchar(255), type varchar(255), url varchar(255), primary key (jpaId));
create table Repository (jpaId bigint not null, description varchar(255), fork boolean not null, full_name varchar(255), html_url varchar(255), id bigint, isPrivate boolean not null, name varchar(255), url varchar(255), owner_login varchar(255) UNIQUE, primary key (jpaId));
create unique index UK2c3lyrojxlxgdkkwqvsivl7mg on GitHubUser (login);
create unique index notification_id on Notification (id, userId);
create unique index UKkdccl9g909hlemc5l786d4qs7 on Repository (id, owner_login);
alter table Notification add constraint FK5kwjc7d9bp8weijbhe4evjoly foreign key (repository_jpaId) references Repository;
alter table Notification add constraint FK70jp81julgkk51h0nqrh2f48u foreign key (subject_jpaId) references NotificationSubject;
alter table NotificationMetaData add constraint FK3araq3cuv61t5njdjyojwjrnm foreign key (applicationAccount_id) references ApplicationAccount;
alter table Repository add constraint FK2l6b04rxmo7pyae287jbtwprr foreign key (owner_login) references GitHubUser (login);